export enum MySqlErrorMessage {
    ER_DUP_ENTRY = 'Entrada duplicada',
    ER_NO_DEFAULT_FOR_FIELD = 'No hay valor predeterminado para el campo',
    ER_ROW_IS_REFERENCED_2 = 'La fila está referenciada por otra tabla',
    ER_NO_REFERENCED_ROW_2 = 'La fila referenciada no existe',
    ER_DATA_TOO_LONG = 'Datos demasiado largos',
    ER_BAD_NULL_ERROR = 'Columna no puede ser nula',
    ER_ROW_IS_REFERENCED = 'La fila está referenciada por otra tabla',
    ER_TRUNCATED_WRONG_VALUE_FOR_FIELD = 'Valor truncado incorrectamente',
    ER_PARSE_ERROR = 'Error de sintaxis',
    ER_WRONG_FIELD_WITH_GROUP = 'Campo incorrecto con grupo',
    ER_NO_SUCH_TABLE = 'La tabla no existe',
    ER_WRONG_VALUE_COUNT_ON_ROW = 'Número de valores incorrecto en la fila',
    ER_WRONG_TYPE_FOR_VAR = 'Tipo incorrecto para la variable',
    ER_WRONG_DB_NAME = 'Nombre de base de datos incorrecto',
    ER_WRONG_TABLE_NAME = 'Nombre de tabla incorrecto',
    ER_UNKNOWN_TABLE = 'Tabla desconocida',
    ER_FIELD_SPECIFIED_TWICE = 'Campo especificado dos veces',
    ER_ILLEGAL_REFERENCE = 'Referencia ilegal',
    ER_CANT_DO_THIS_DURING_AN_TRANSACTION = 'No se puede hacer esto durante una transacción',
    ER_READ_ONLY_TRANSACTION = 'Transacción de solo lectura',
    ER_NO_REFERENCED_ROW = 'No hay fila referenciada',
    ER_DUP_KEY = 'Clave duplicada',
  }